### ISSUE TITLE
Mobile Website Sidebar Issues

### ISSUE THREAD

**Issue by ghost** [alduris/mod-map#1]
This seems to be a minor unimportant issue. When I slide the sidebar button, I slide out of the page. At this point, continuing to manually shrink the sidebar will shrink the entire page (this issue also occurs when manually shrinking the left sidebar), or continuing to swipe down when sliding the left area list to the bottom will also slide out of the page.
![IMG_20241028_214723](https://github.com/user-attachments/assets/39746b42-6f29-4e0f-a46b-f1044547d47f)
![IMG_20241028_214754](https://github.com/user-attachments/assets/9676a738-7c43-4ee9-96cc-c7cd591af41c)

**Comment by alduris** [comment]
What browser is this? I know it works for sure on Safari and desktop Firefox. Also what kind of device.

**Comment by ghost** [comment]
**System:** Android 14
**Browser:** Chrome 130.0.6723.74

I accidentally discovered this issue, but it doesn't have a significant impact. After all, there shouldn't be anyone like me who slides the sidebar randomly. :D

https://github.com/user-attachments/assets/7c35ef77-405c-4552-96e9-8d9fa2d49a67


https://github.com/user-attachments/assets/95501c0f-6363-4b43-b9e0-7ba8f51ebdbb
